name: Build Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build release from (e.g., 0.26)'
        required: true
        type: string
      draft:
        description: 'Create as draft release'
        type: boolean
        default: false
      prerelease:
        description: 'Mark as pre-release'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn clean install
      
      - name: Find and rename JAR file
        id: rename-jar
        run: |
          # Find the original JAR
          ORIGINAL_JAR=$(find target/ -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" -not -name "*-tests.jar" | head -n 1)
          
          # Define the target name
          RENAMED_JAR="target/keycloak-magic-link.jar"
          
          # Copy the JAR with the new name
          cp "$ORIGINAL_JAR" "$RENAMED_JAR"
          
          # Output the paths
          echo "original_jar_path=$ORIGINAL_JAR" >> $GITHUB_OUTPUT
          echo "renamed_jar_path=$RENAMED_JAR" >> $GITHUB_OUTPUT
          
          # For debugging
          echo "Original JAR: $ORIGINAL_JAR"
          echo "Renamed JAR: $RENAMED_JAR"
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ steps.rename-jar.outputs.renamed_jar_path }}
          name: Release ${{ github.event.inputs.tag }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
